name: Java CI with Gradle

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Cache gradle files
      uses: actions/cache@v2
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('*.gradle') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    - name: Clean up
      run: rm -f gradle.properties

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Create Release
      run: ./gradlew createRelease --stacktrace

    - uses: actions/upload-artifact@v2
      with:
        name: TC UHC distribution for ${{ github.sha }}
        path: ./build/distributions
